# Gradle
org.gradle.jvmargs=-Xmx8G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# Parchment
parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17

# Minecraft
minecraft_version=1.21.1
minecraft_version_range=[1.21.1]

# NeoForge
neo_version=21.1.234
loader_version_range=[1,)

# Dependencies
jei_version=19.25.0.322

# Mod properties
mod_id=baobabtree
mod_name=Baobab Tree
mod_license=MIT License
mod_version=1.0r
mod_group_id=de.artemis.baobabtree
mod_authors=Doomed_Artemis
mod_description=Baobab-themed trees, worldgen, and natural content for Minecraft NeoForge.
