# Gradle
org.gradle.jvmargs=-Xmx8G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# Minecraft
minecraft_version=26.1
minecraft_version_range=[26.1]

# NeoForge
neo_version=26.1.0.19-beta
loader_version_range=[1,)

# Dependencies
jei_version=29.2.0.21

# Mod properties
mod_id=baobabtree
mod_name=Baobab Tree
mod_license=MIT License
mod_version=1.2.1r
mod_group_id=de.artemis.baobabtree
mod_authors=DoomedArtemis
mod_description=Mod centered around massive, atmospheric baobab trees—featuring colossal savanna landmarks, sprawling roots, hollow ancient trunks, hanging fruit pods, leaf litter, and a complete custom wood set.
